// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sftp} from '../models';

export function AutoStartEnabled():Promise<void>;

export function CreateTunnel(arg1:config.Tunnel):Promise<void>;

export function Cwd():Promise<string>;

export function DeleteLocal(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function HomeDir():Promise<string>;

export function ImportCommand(arg1:string):Promise<Array<config.Tunnel>>;

export function Init(arg1:any):Promise<void>;

export function ListHosts():Promise<Array<string>>;

export function ListHostsDetailed():Promise<Array<config.Host>>;

export function ListLocal(arg1:string):Promise<Array<sftp.Item>>;

export function ListRecentSFTP():Promise<Array<config.RecentSFTP>>;

export function ListTunnels():Promise<Array<config.Tunnel>>;

export function MkdirLocal(arg1:string):Promise<void>;

export function OnShutdown():Promise<void>;

export function PickLocalDir():Promise<string>;

export function PickLocalFile():Promise<string>;

export function RenameLocal(arg1:string,arg2:string):Promise<void>;

export function SftpConnect(arg1:string):Promise<void>;

export function SftpConnected(arg1:string):Promise<boolean>;

export function SftpDisconnect(arg1:string):Promise<void>;

export function SftpGet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpGetDir(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpHome(arg1:string):Promise<string>;

export function SftpList(arg1:string,arg2:string,arg3:string):Promise<Array<sftp.Item>>;

export function SftpMkdir(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpPut(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpRemove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartTunnel(arg1:string):Promise<void>;

export function StatLocal(arg1:string):Promise<number>;

export function StopTunnel(arg1:string):Promise<void>;

export function TunnelStates():Promise<{[key: string]: string}>;

export function UpdateTunnel(arg1:config.Tunnel):Promise<void>;
