// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStartEnabled() {
  return window['go']['main']['App']['AutoStartEnabled']();
}

export function CreateTunnel(arg1) {
  return window['go']['main']['App']['CreateTunnel'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function ImportCommand(arg1) {
  return window['go']['main']['App']['ImportCommand'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['App']['Init'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function OnShutdown() {
  return window['go']['main']['App']['OnShutdown']();
}

export function SftpGet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpGet'](arg1, arg2, arg3, arg4);
}

export function SftpList(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpList'](arg1, arg2, arg3);
}

export function SftpMkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2, arg3);
}

export function SftpPut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpPut'](arg1, arg2, arg3, arg4);
}

export function SftpRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2, arg3);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function UpdateTunnel(arg1) {
  return window['go']['main']['App']['UpdateTunnel'](arg1);
}
