// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sftp} from '../models';

export function AutoStartEnabled():Promise<void>;

export function CreateTunnel(arg1:config.Tunnel):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function ImportCommand(arg1:string):Promise<Array<config.Tunnel>>;

export function Init(arg1:any):Promise<void>;

export function ListHosts():Promise<Array<string>>;

export function ListTunnels():Promise<Array<config.Tunnel>>;

export function OnShutdown():Promise<void>;

export function PickLocalFile():Promise<string>;

export function SftpGet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpList(arg1:string,arg2:string,arg3:string):Promise<Array<sftp.Item>>;

export function SftpMkdir(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpPut(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpRemove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function UpdateTunnel(arg1:config.Tunnel):Promise<void>;
