// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStartEnabled() {
  return window['go']['main']['App']['AutoStartEnabled']();
}

export function CreateTunnel(arg1) {
  return window['go']['main']['App']['CreateTunnel'](arg1);
}

export function Cwd() {
  return window['go']['main']['App']['Cwd']();
}

export function DeleteLocal(arg1) {
  return window['go']['main']['App']['DeleteLocal'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function ImportCommand(arg1) {
  return window['go']['main']['App']['ImportCommand'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['App']['Init'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListHostsDetailed() {
  return window['go']['main']['App']['ListHostsDetailed']();
}

export function ListLocal(arg1) {
  return window['go']['main']['App']['ListLocal'](arg1);
}

export function ListRecentSFTP() {
  return window['go']['main']['App']['ListRecentSFTP']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function MkdirLocal(arg1) {
  return window['go']['main']['App']['MkdirLocal'](arg1);
}

export function OnShutdown() {
  return window['go']['main']['App']['OnShutdown']();
}

export function PickLocalDir() {
  return window['go']['main']['App']['PickLocalDir']();
}

export function PickLocalFile() {
  return window['go']['main']['App']['PickLocalFile']();
}

export function RenameLocal(arg1, arg2) {
  return window['go']['main']['App']['RenameLocal'](arg1, arg2);
}

export function SftpConnect(arg1) {
  return window['go']['main']['App']['SftpConnect'](arg1);
}

export function SftpConnected(arg1) {
  return window['go']['main']['App']['SftpConnected'](arg1);
}

export function SftpDisconnect(arg1) {
  return window['go']['main']['App']['SftpDisconnect'](arg1);
}

export function SftpGet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpGet'](arg1, arg2, arg3, arg4);
}

export function SftpHome(arg1) {
  return window['go']['main']['App']['SftpHome'](arg1);
}

export function SftpList(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpList'](arg1, arg2, arg3);
}

export function SftpMkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2, arg3);
}

export function SftpPut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpPut'](arg1, arg2, arg3, arg4);
}

export function SftpRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2, arg3);
}

export function SftpRename(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3, arg4);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StatLocal(arg1) {
  return window['go']['main']['App']['StatLocal'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TunnelStates() {
  return window['go']['main']['App']['TunnelStates']();
}

export function UpdateTunnel(arg1) {
  return window['go']['main']['App']['UpdateTunnel'](arg1);
}
